## View vs copy

In [1]:
x = [1, 2, 3]

In [2]:
y = x

In [4]:
y[0] = 42

In [5]:
y

[42, 2, 3]

In [6]:
x

[42, 2, 3]

En python, la création d'une nouvelle variable à partir d'un objet n'entrainne pas forcément la création d'un nouvel objet, mais va simplement créer un pointeur sur l'objet originel en mémoire.

In [7]:
id(x)

4423204736

In [8]:
id(y)

4423204736

In [7]:
id(x) == id(y)

True

### Comment copier un objet ?

In [9]:
%reset -f

In [8]:
x = [1, 2, 3]

In [9]:
y = x.copy()

In [10]:
y[0] = 42

In [11]:
x

[1, 2, 3]

In [12]:
y

[42, 2, 3]

In [13]:
id(x) == id(y)

False

### Exemple qui nous concerne

In [16]:
import copy
import pandas as pd
import numpy as np

In [17]:
df = pd.DataFrame({"A": np.random.randint(0,100, 6)})

In [18]:
df

    A
0  66
1  54
2  21
3  56
4  88
5  96

In [19]:
df2 = df.loc[0:3]

In [20]:
df2

    A
0  66
1  54
2  21
3  56

In [21]:
df2.loc[1] = 666

/var/folders/l5/p4f2y4qd0jj4n34zysyp82540000gn/T/ipykernel_83733/3316915151.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[1] = 666

In [22]:
df2

     A
0   66
1  666
2   21
3   56

In [23]:
df

     A
0   66
1  666
2   21
3   56
4   88
5   96

In [25]:
id(df)

4538366800

In [26]:
id(df2)

4424314832

⚠️ Même si `df1` et `df2` ne sont pas le même objet, `df2` est une sous-partie de `df1` et toute modification de `df2` **risque** de modifier `df1`

In [27]:
%reset -f

In [28]:
import copy
import pandas as pd
import numpy as np

In [29]:
df = pd.DataFrame({"A": np.random.randint(0,100,6)})

In [30]:
df2 = df.loc[0:3].copy()

In [31]:
df2.loc[1] = 666

In [32]:
df2

     A
0   11
1  666
2   55
3   93

In [33]:
df

    A
0  11
1   9
2  55
3  93
4   0
5  62

### Si votre objet est complexe/profond et que vous souhaitez créer une copie de tous ses éléments et sous éléments

In [ ]:
import copy

In [ ]:
df2 = copy.deepcopy(df.loc[0:3])

Est-ce que pandas va réaliser une vue ou une copie ?   
Est-ce qu'une vue va modifier la DataFrame originale ?
Dur à savoir...

In [ ]:
%reset -f

In [ ]:
import copy
import pandas as pd
import numpy as np

In [34]:
df = pd.DataFrame({"A": np.random.randint(0,100,6)})
df2 = df.loc[0:3]
df2.loc[1] = 666
df

/var/folders/l5/p4f2y4qd0jj4n34zysyp82540000gn/T/ipykernel_93403/2609933918.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[1] = 666

     A
0   45
1  666
2   79
3   74
4   45
5   68

In [35]:
df = pd.DataFrame({"A": np.random.randint(0,100,6)})
df2 = df.loc[0:3]
df2.loc[1] = "coucou"
df

/var/folders/l5/p4f2y4qd0jj4n34zysyp82540000gn/T/ipykernel_93403/1165333555.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'coucou' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df2.loc[1] = "coucou"

    A
0  94
1  66
2  41
3   5
4  51
5  64

Pandas a introduit le Copy on Write, qui peut être activé en option et qui devrait prémunir l'utilisateur de ce genre de bévues. Il devrait être activé par défaut dès pandas 3.0 !  
Pour en savoir plus: https://towardsdatascience.com/deep-dive-into-pandas-copy-on-write-mode-part-i-26982e7408c6