## Les erreurs en Python

Quand on code, si on code suffisamment longtemps on va être confronté à des erreurs:
1. Les erreurs que l'on veut passer sans casser notre programme
2. Les erreurs qui doivent terminer les programme

### Try-Except (finally) 
Quand on a une erreur que l'on veut passer sans casser notre programme.

doc python officielle : https://docs.python.org/3/tutorial/errors.html

In [2]:
try:
    print("Coucou " + "hello")
except:
    print("bouuuu")

Coucou hello

In [4]:
try:
    print(3 + "hello")
except:
    print("bouuuu")

bouuuu

---------

##### Printer l'exception si on veut savoir pourquoi cela n'a pas marché

In [5]:
try:
    print(3 + "hello")
except Exception as e:
    print(e)

unsupported operand type(s) for +: 'int' and 'str'

In [6]:
try:
    print(3 + "hello")
except Exception as e:
    print(repr(e))
    print("coucou")
print("goodbye")

TypeError("unsupported operand type(s) for +: 'int' and 'str'")
coucou
goodbye

#### Lever l'exception que si c'est bien l'exception que l'on attend qui a été levée

In [9]:
try:
    print(3 + variable_non_definie)
    print(3 + "hello")
except TypeError as e:
    print(e)
print("coucou")

NameError: name 'variable_non_definie' is not defined

In [10]:
try:
    print(3 + variable_non_definie)
    print(3 + "hello")
except (TypeError, NameError) as e:
    print(e)
print("coucou")

name 'variable_non_definie' is not defined
coucou

In [4]:
try:
    import un_package_qui_nexiste_pas
    print(3 + "hello")
except TypeError as e:
    print(e)
print(e)
print("Coucou !")

ModuleNotFoundError: No module named 'un_package_qui_nexiste_pas'

In [18]:
try:
    import un_package_qui_nexiste_pas
    print(3 + "hello")
except (TypeError, ModuleNotFoundError) as e:
    print(e)
print("coucou")

No module named 'un_package_qui_nexiste_pas'
coucou

#### Mais pour quoi faire ?

In [12]:
b = 3
while True:
    a = input("renseignez quoi ajouter à b: ")
    try:
        a = float(a)
    except ValueError:
        pass
    try:
        print(a + b)
        print("l'école est finie !")
        break
    except TypeError as e:
        #print(e)
        print("On ne peut pas additionner les int et les string, mais la vie continue ☀️ !")

renseignez quoi ajouter à b:  3

6.0
l'école est finie !

In [11]:
b = 3
while True:
    a = input("renseignez quoi ajouter à b: ")

    try:
        print(float(a) + b)
        print("l'école est finie !")
        break
    except(TypeError,ValueError) as e:
        #print(e)
        print("On ne peut pas additionner les int et les string, mais la vie continue ☀️ !")

renseignez quoi ajouter à b:  coucou

On ne peut pas additionner les int et les string, mais la vie continue ☀️ !

renseignez quoi ajouter à b:  coucou

On ne peut pas additionner les int et les string, mais la vie continue ☀️ !

renseignez quoi ajouter à b:  12

15.0
l'école est finie !

In [13]:
float("32e10")

320000000000.0

Mais en data science ?

In [23]:
import os

In [26]:
import pandas as pd
from urllib.error import URLError
#from IPython.display import display
import os
try:
    df = pd.read_csv(
        "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/"
        +"dpc-covid19-ita-province-20200225.csv")
    try:
        os.mkdir("./data")
    except FileExistsError:
        print("Folder already exists")
        
    df.to_csv("./data/covid_italie.csv")
    display(df)
except URLError: #imaginons que le csv soit supprimé par l'utilisateur
    print("URL ERROR, va lire le fichier en cache")
    df = pd.read_csv("./data/covid_italie.csv")

    display(df)

Folder already exists

,data,stato,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,lat,long,totale_casi,note
0,2020-02-25T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0,NaN
1,2020-02-25T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0,NaN
2,2020-02-25T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0,NaN
3,2020-02-25T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0,NaN
4,2020-02-25T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
123,2020-02-25T18:00:00,ITA,5,Veneto,26,Treviso,TV,45.667546,12.245074,1,NaN
124,2020-02-25T18:00:00,ITA,5,Veneto,27,Venezia,VE,45.434905,12.338452,7,NaN
125,2020-02-25T18:00:00,ITA,5,Veneto,28,Padova,PD,45.406930,11.876087,30,NaN
126,2020-02-25T18:00:00,ITA,5,Veneto,29,Rovigo,RO,45.071073,11.790070,0,NaN
127,2020-02-25T18:00:00,ITA,5,Veneto,999,In fase di definizione/aggiornamento,NaN,NaN,NaN,5,NaN

Écrivez une fonction de mise en cache d'un fichier csv qui est en ligne.
- Si le fichier est enregistré, ne pas le télécharger et le lire.
- Si le fichier n'est pas enregistré, le télécharger/lire, et l'enregistrer.

In [30]:
url = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province-20200225.csv"

In [64]:
def mise_en_cache_fichier_csv(url_csv, file_path=None):
    """une docstring
    Lis une url de fichier csv en ligne
    sauf si le fichier est déjà enregistré
    dans ce cas là, le lis localement
    ----
    return
    DataFrame
    """
    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print("pas lu le csv sur l'ordinateur")
        df = pd.read_csv(url_csv)
        df.to_csv(file_path,index=False)
    return df

In [32]:
import pandas as pd

In [35]:
df = pd.read_csv(url)
df.to_csv("fihchier_exercice_cache.csv")

In [56]:
try:
    df = pd.read_csv("fihchier_exercice_cache.csv")
except FileNotFoundError:
    print("pas lu le csv sur l'ordinateur")
    df = pd.read_csv(url)
    df.to_csv("fihchier_exercice_cache.csv",index=False)

In [48]:
df_save = df.copy()

In [57]:
df.head()

,data,stato,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,lat,long,totale_casi,note
0,2020-02-25T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0,NaN
1,2020-02-25T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0,NaN
2,2020-02-25T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0,NaN
3,2020-02-25T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0,NaN
4,2020-02-25T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,NaN,NaN,0,NaN

In [51]:
df_save.head()

,data,stato,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,lat,long,totale_casi,note
0,2020-02-25T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0,NaN
1,2020-02-25T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0,NaN
2,2020-02-25T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0,NaN
3,2020-02-25T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0,NaN
4,2020-02-25T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,NaN,NaN,0,NaN

Il est normalement conseillé de définir l'erreur(s) levée(s) pour définir l'exception.
Sur une librairie/base de code conséquente, ça facilite le déboguage et permettra au programme de crasher si une erreur non prévue arrive.

Sur de la data science en jupyter notebook ¯\_(ツ)_/¯ (on gagne du temps a ne pas les définir et à priori on fera quelque chose de plus propre en production).

## Les asserts

In [28]:
assert 3==3

In [30]:
assert 3 == 4

AssertionError:

Un assert s'assure qu'une condition est vraie pour que le programme continue.

Mais à quoi ça sert ?:
1. Permet de faire en sorte que le code casse s'il ne se comporte pas comme prévu
2. Permet d'auto-documenter son code 


Utiliser beaucoup d'assert est une bonne chose.   



Il est même souvent utile d'écrire un assert (un test) pour définir ce que l'on veut  que le code fasse, avant d'écrire le code : c'est la base du **Test driven development**.

Mais à quoi ça peut servir en data science ?  

C'est souvent utile pour tester les données. Par exemple qu'après des manipulations, le nombre d'observation soit égal aux observations espérées (surtout après des merge).

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province-20200225.csv")

assert len(df)>2000 #ici on teste que l'on a au moins 20 lignes dans la table téléchargée

AssertionError:

C'est aussi la base des tests unitaire (ou d'intégration) qui permet de faire du CI (jenkins, Travis, Gitlab et Github CI etc).
C'est une des bases importantes du [MLOps](https://en.wikipedia.org/wiki/MLOps)

[travis](https://travis-ci.org/github/adrienpacifico/adrienpacifico.github.io/builds/768587169)

### Exemple de TDD avec pytest pour faire un mini ci

En TDD on écrit les tests d'abord !

In [34]:
%pip install ipytest

Collecting ipytest
  Downloading ipytest-0.13.3-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: ipython in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipytest) (8.15.0)
Requirement already satisfied: packaging in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipytest) (23.1)
Collecting pytest>=5.4 (from ipytest)
  Using cached pytest-7.4.3-py3-none-any.whl.metadata (7.9 kB)
Collecting iniconfig (from pytest>=5.4->ipytest)
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting pluggy<2.0,>=0.12 (from pytest>=5.4->ipytest)
  Using cached pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: backcall in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.2.0)
Requirement already satisfied: decorator in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.18.1)
Requirement already satisfied: matplotlib-inline in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.1.6)
Requirement already satisfied: pickleshare in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (2.15.1)
Requirement already satisfied: stack-data in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.2.0)
Requirement already satisfied: traitlets>=5 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (4.8.0)
Requirement already satisfied: appnope in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from ipython->ipytest) (0.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from jedi>=0.16->ipython->ipytest) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from pexpect>4.3->ipython->ipytest) (0.7.0)
Requirement already satisfied: wcwidth in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->ipytest) (0.2.5)
Requirement already satisfied: executing in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from stack-data->ipython->ipytest) (0.8.3)
Requirement already satisfied: asttokens in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from stack-data->ipython->ipytest) (2.0.5)
Requirement already satisfied: pure-eval in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from stack-data->ipython->ipytest) (0.2.2)
Requirement already satisfied: six in /Users/adrienpacifico/anaconda3/envs/python_data_science/lib/python3.11/site-packages (from asttokens->stack-data->ipython->ipytest) (1.16.0)
Downloading ipytest-0.13.3-py3-none-any.whl (14 kB)
Using cached pytest-7.4.3-py3-none-any.whl (325 kB)
Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Installing collected packages: pluggy, iniconfig, pytest, ipytest
Successfully installed iniconfig-2.0.0 ipytest-0.13.3 pluggy-1.3.0 pytest-7.4.3
Note: you may need to restart the kernel to use updated packages.

In [35]:
import ipytest
ipytest.autoconfig()

On va faire une fonction qui crée une division entière.
On va l'appelerè `division_entiere`

In [48]:
def division_entiere(quotient, dividend):
    return quotient//dividend

In [56]:
isinstance(4//0, ZeroDivisionError)

ZeroDivisionError: integer division or modulo by zero

In [61]:
%%ipytest
def test_division_entiere_type():
    assert isinstance(division_entiere(10,5), int)
def test_division_entiere_result_1():
    assert division_entiere(10,2) == 5
def test_division_entiere_negative():
    assert division_entiere(-10,2) == -5
def test_division_entiere_with_rest():
    assert division_entiere(11,2) == 5
def test_error_if_divide_by_zero():
    try:
        4//0
    except Exception as e:
        print(e)
        assert str(e) == 'integer division or modulo by zero'

.....                                                                                        [100%]
5 passed in 0.01s

On a bien une fonction de division entière qui fonctionne.
Maintenant l'utilisateur nous demande de modifier la fonction pour accepter des nombre en string dans la fonction.

In [71]:
def division_entiere(quotient, dividend):
    quotient = int(quotient)
    dividend = int(dividend)
    return quotient//dividend

Modifier la fonction et écrivez le tests pour que:
- la fonction marche avec des nombres non entiers
- la fonction marche avec des nombres en string
_____
- la fonction marche avec des nombres en toute lettres 
`division_entiere("onze", "deux") == 5`, pour cela vous pourrez vous aider de la librairie `text2num`

In [79]:
%pip install text2num

Collecting text2num
  Downloading text2num-2.5.0.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: text2num
  Building wheel for text2num (setup.py) ... done
  Created wheel for text2num: filename=text2num-2.5.0-py3-none-any.whl size=58659 sha256=7b2e54591ca815e1de8aaf9954ca8c487c6affa06f229d116990955de2a6f291
  Stored in directory: /Users/adrienpacifico/Library/Caches/pip/wheels/ac/04/76/d6d128340a3efc998468fd8da42f3b8148ab466fa735fdd726
Successfully built text2num
Installing collected packages: text2num
Successfully installed text2num-2.5.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
from text_to_num import text2num
text2num("mille neuf cents quatre-vingt dix","fr")

1990

In [77]:
%%ipytest
def test_division_entiere_type():
    assert isinstance(division_entiere(10,5), int)
def test_division_entiere_result_1():
    assert division_entiere(10,2) == 5
def test_division_entiere_negative():
    assert division_entiere(-10,2) == -5
def test_division_entiere_with_rest():
    assert division_entiere(11,2) == 5
def test_error_if_divide_by_zero():
    try:
        4//0
    except Exception as e:
        print(e)
        assert str(e) == 'integer division or modulo by zero'
def test_nombre_en_string_1():
    assert division_entiere("10","2") == 5
def test_nombre_en_string_2():
    assert division_entiere("11","2") == 5
def test_div_nombre_non_entiers():
    assert division_entiere(25,2.9) == 8

.......F                                                                                     [100%]
============================================= FAILURES =============================================
___________________________________ test_div_nombre_non_entiers ____________________________________

    def test_div_nombre_non_entiers():
>       assert division_entiere(25,2.9) == 8
E       assert 12 == 8
E        +  where 12 = division_entiere(25, 2.9)

/var/folders/l5/p4f2y4qd0jj4n34zysyp82540000gn/T/ipykernel_17776/1692442340.py:20: AssertionError
===================================== short test summary info ======================================
FAILED t_c5ea571a7f9c488b8c51e2dfa7f36c21.py::test_div_nombre_non_entiers - assert 12 == 8
1 failed, 7 passed in 0.02s

In [ ]:
%%ipytest

# define the tests

def test_my_func1():
    assert my_func(37,6) == 12
def test_my_func2():
    assert my_func(36, 6) == 12

In [100]:
def return_none():
    return None

In [103]:
assert return_none() is None

In [104]:
2==None

False

In [161]:
%pip install text2num

Collecting text2num
  Downloading text2num-2.5.0.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: text2num
  Building wheel for text2num (setup.py) ... done
  Created wheel for text2num: filename=text2num-2.5.0-py3-none-any.whl size=58659 sha256=d134075c3d0384f9bd958c37ad4323348783d4f4ae90798fcccfaa2593dcebf4
  Stored in directory: /home/jovyan/.cache/pip/wheels/ac/04/76/d6d128340a3efc998468fd8da42f3b8148ab466fa735fdd726
Successfully built text2num
Installing collected packages: text2num
Successfully installed text2num-2.5.0
Note: you may need to restart the kernel to use updated packages.

In [164]:
from text_to_num import text2num
text2num("cinq","fr")

5

1990

In [ ]:
import ipytest
ipytest.autoconfig()

In [175]:
hab_surface_by_ville = {"Marseille":{"nombre_habitants":200_000,"surface":6*10**7}, "Paris":{"nombre_habitants":400_000,"surface":10**7},
"Montfort":{"nombre_habitants":0,"surface":10_000}, "Dijon":{"nombre_habitants":"200_000","surface":"60_000_000"},
                        "Troyes":{"nombre_habitants":"dix milles","surface":"un million"}
                       }

In [176]:
for ville in hab_surface_by_ville.keys():
    print(ville)
    hab_surface_by_ville[ville]["m2_par_habitants"] = division_entiere(
                                     hab_surface_by_ville[ville]["surface"],
                                    hab_surface_by_ville[ville]["nombre_habitants"],
                                                        )
print(hab_surface_by_ville)

Mrseille
Paris
Montfort
Dijon
Troyes
{'Mrseille': {'nombre_habitants': 200000, 'surface': 60000000, 'm2_par_habitants': 300}, 'Paris': {'nombre_habitants': 400000, 'surface': 10000000, 'm2_par_habitants': 25}, 'Montfort': {'nombre_habitants': 0, 'surface': 10000, 'm2_par_habitants': None}, 'Dijon': {'nombre_habitants': '200_000', 'surface': '60_000_000', 'm2_par_habitants': 300}, 'Troyes': {'nombre_habitants': 'dix milles', 'surface': 'un million', 'm2_par_habitants': 100}}

In [154]:
def division_entiere(dividende, diviseur):
    if diviseur == 0:
        return None
    else:
        return int(dividende)//int(diviseur)

In [168]:
from text_to_num import text2num
text2num("mille neuf cents quatre-vingt dix","fr")

1990

In [184]:
def division_entiere(dividende, diviseur):
    if diviseur == 0:
        return None
    else:
        try:
            return int(dividende)//int(diviseur)
        except ValueError:
            dividende = text2num(dividende,"fr")
            diviseur = text2num(diviseur,"fr")
            return dividende//diviseur

In [183]:
%%ipytest
def test_division_entiere_0():
    assert division_entiere(10,5) == 2
def test_division_entiere_01():
    assert division_entiere(6,2) == 3
def test_division_entiere_1():
    assert division_entiere(13,2) == 6
def test_division_entiere_2():
    assert division_entiere(15,2) == 7
def test_division_entiere_par_zero():
    assert division_entiere(23,0) is None


def test_division_entiere_avec_string_1():
    assert division_entiere(10,"5") == 2 
def test_division_entiere_avec_string_2():
    assert division_entiere("10",5) == 2 
def test_division_entiere_avec_string_3():
    assert division_entiere("10","0") is None
def test_division_entiere_avec_nombre_en_lettres_0():
    assert division_entiere("dix","cinq") == 2
def test_division_entiere_avec_nombre_en_lettres_1():
    assert division_entiere("un million","dix mille") == 100
def test_division_entiere_avec_nombre_en_lettres_1():
    assert division_entiere("mille neuf cent quatre-vingt-dix-neuf",
                            "quatre cent vingt-quatre") == 4
def test_division_entiere_avec_string_0():
    assert division_entiere("10","5") == 2 
def test_division_entiere_avec_1nombre_en_lettres_autre_en_int():
    assert division_entiere("dix",5) == 2

.........FF                                                                                  [100%]
============================================= FAILURES =============================================
__________________________ test_division_entiere_avec_nombre_en_lettres_0 __________________________

    def test_division_entiere_avec_nombre_en_lettres_0():
>       assert division_entiere("dix","cinq") == 2

/tmp/ipykernel_39813/1652768601.py:21:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dividende = 'dix', diviseur = 'cinq'

    def division_entiere(dividende, diviseur):
>       if int(diviseur) == 0:
E       ValueError: invalid literal for int() with base 10: 'cinq'

/tmp/ipykernel_39813/667153445.py:2: ValueError
__________________________ test_division_entiere_avec_nombre_en_lettres_1 __________________________

    def test_division_entiere_avec_nombre_en_lettres_1():
>       assert division_entiere("mille neuf cent quatre-vingt-dix-neuf",
                                "quatre cent vingt-quatre") == 4

/tmp/ipykernel_39813/1652768601.py:25:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dividende = 'mille neuf cent quatre-vingt-dix-neuf', diviseur = 'quatre cent vingt-quatre'

    def division_entiere(dividende, diviseur):
>       if int(diviseur) == 0:
E       ValueError: invalid literal for int() with base 10: 'quatre cent vingt-quatre'

/tmp/ipykernel_39813/667153445.py:2: ValueError
===================================== short test summary info ======================================
FAILED t_84202611e1d84b36ada95c48a41e785e.py::test_division_entiere_avec_nombre_en_lettres_0 - ValueError: invalid literal for int() with base 10: 'cinq'
FAILED t_84202611e1d84b36ada95c48a41e785e.py::test_division_entiere_avec_nombre_en_lettres_1 - ValueError: invalid literal for int() with base 10: 'quatre cent vingt-quatre'
2 failed, 9 passed in 0.03s

In [151]:
%pip install inflect

Collecting inflect
  Downloading inflect-7.0.0-py3-none-any.whl (34 kB)
Collecting pydantic>=1.9.1 (from inflect)
  Downloading pydantic-2.4.2-py3-none-any.whl (395 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.8/395.8 kB 11.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from inflect) (4.7.1)
Collecting annotated-types>=0.4.0 (from pydantic>=1.9.1->inflect)
  Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.10.1 (from pydantic>=1.9.1->inflect)
  Downloading pydantic_core-2.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 7.5 MB/s eta 0:00:00a 0:00:01m
Installing collected packages: pydantic-core, annotated-types, pydantic, inflect
Successfully installed annotated-types-0.6.0 inflect-7.0.0 pydantic-2.4.2 pydantic-core-2.10.1
Note: you may need to restart the kernel to use updated packages.

#### Exemple général

In [50]:
def my_func(x):
    return (x // 2) * 2

In [53]:
(37//6)*2

12

In [62]:
def my_func(x, y):
    """
    Fait division entière par 
    et multiplie le résultat par 2
    """
    return (x // y) * 2

In [63]:
my_func(43,2)

42

In [72]:
%%ipytest

# define the tests

def test_my_func1():
    assert my_func(37,6) == 12
def test_my_func2():
    assert my_func(36, 6) == 12
def test_my_func3():
    assert my_func(40, 6) == 12
def test_my_func4():
    assert my_func(43,2) == 42
def test_my_func5():
    assert my_func(64,2) == 64
def test_my_func6():
    assert my_func(65,2) == 64
    
    
    
def my_func(x,y):
    """
    Fait division entière par 
    et multiplie le résultat par 2
    """
    return 2 * (x // y)

......                                                                                       [100%]
6 passed in 0.01s

In [76]:
%%ipytest

import pytest

def my_func(x):
    """
    Fait division entière par 
    et multiplie le résultat par 2
    """
    return (x // 2)*2

@pytest.mark.parametrize('input,expected', [
    (0, 0),
    (1, 0),
    (2, 2),
    (3, 2),
])
def test_parametrized(input, expected):
    assert my_func(input) == expected
    
@pytest.fixture
def my_fixture():
    return 42
    
    
def test_fixture(my_fixture):
    assert my_fixture == 42

.....                                                                                        [100%]
5 passed in 0.01s

Exemple appliqué :

In [ ]:
#On écrit ce que l'on veut que la fonction fasse

def download_or_load(url=None, cache_path="./data"):
    """
    Télécharge un csv via une url en ligne
    À défaut, charge la données correspondante en cache
    """

In [ ]:
### test download_or_load si la donnée est disponible
def test_dowload_or_load_if_correct_url():
    """
    1- Crée le dossier /data s'il n'existe pas
    2- Essaye de télécharger un csv via un lien qui marche et retourne 
    """

In [18]:
### Terminer, puis faire un exemple ou on veut rajouter que l'on veut que des url qui se terminent pas csv